Criação de testes de CRUD do usuário
danielafdc/api-tests pull request #1
Opened 2021-03-14 23:42 UTC by danielafdc

2021-03-15 15:18 UTC, samycici requested changes
fiz uns comentários pedindo algumas mudanças, além disso roda o `npm run lint` ele vai mostrar alguns problemas de espaçamento, falta de linha no final do arquivo e tal, dai vc já corrige e garantimos que vamos seguir a mesma padronização :)

2021-03-15 15:18 UTC, samycici commented on usuarios/delete-usuarios.spec.js
> +  done()
não precisa desse done, o async/await já se resolve sozinho

```suggestion
beforeEach( async () => {
  usuario = user.dadosDoUsuario()

  const response_user = await user.criarUsuario(usuario)

  user_id = await response_user.body._id
```

2021-03-15 15:18 UTC, samycici commented on usuarios/put-usuarios.spec.js
> +  done()
não precisa desse done, o async/await já se resolve sozinho

```suggestion
beforeEach( async () => {
  usuario = user.dadosDoUsuario()

  const response_user = await user.criarUsuario(usuario)

  user_id = await response_user.body._id
```

2021-03-15 15:18 UTC, samycici commented on usuarios/delete-usuarios.spec.js
> +var user_id
```suggestion
let usuario
let user_id
```

faz mais sentido usar o let
ref https://imasters.com.br/front-end/let-const-e-var-nao-e-tudo-mesma-coisa

2021-03-15 15:18 UTC, samycici commented on usuarios/post-usuarios.spec.js
> +var usuario
```suggestion
let usuario
```

faz mais sentido usar o let
ref https://imasters.com.br/front-end/let-const-e-var-nao-e-tudo-mesma-coisa

2021-03-15 15:18 UTC, samycici commented on usuarios/put-usuarios.spec.js
> +var user_id
```suggestion
let usuario
let user_id
```

faz mais sentido usar o let
ref https://imasters.com.br/front-end/let-const-e-var-nao-e-tudo-mesma-coisa

2021-03-15 15:18 UTC, samycici commented on usuarios/delete-usuarios.spec.js
> +var user_id
```suggestion
var usuario
var userId
```
no JS o padrão é camel case, por isso não usamos _ pra nomear

2021-03-15 15:18 UTC, samycici commented on usuarios/delete-usuarios.spec.js
> +  const response_user = await user.criarUsuario(usuario)
```suggestion
  const responseUser = await user.criarUsuario(usuario)
```
no JS o padrão é camel case, por isso não usamos _ pra nomear

2021-03-15 15:18 UTC, samycici commented on usuarios/delete-usuarios.spec.js
> +  user_id = await response_user.body._id
```suggestion
  userId = await responseUser.body._id
```
no JS o padrão é camel case, por isso não usamos _ pra nomear

2021-03-15 15:18 UTC, samycici commented on usuarios/put-usuarios.spec.js
> +var user_id
```suggestion
var userId
```
no JS o padrão é camel case, por isso não usamos _ pra nomear

2021-03-15 15:18 UTC, samycici commented on usuarios/put-usuarios.spec.js
> +  user_id = await response_user.body._id
```suggestion
  const responseUser = await user.criarUsuario(usuario)

  userId = await response_user.body._id
```
no JS o padrão é camel case, por isso não usamos _ pra nomear

2021-03-15 15:18 UTC, samycici commented on usuarios/put-usuarios.spec.js
> +    const response = await testServer.put(rota.rotaUsuarios + '/' + user_id)
```suggestion
    const response = await testServer.put(rota.rotaUsuarios + '/' + userId)
```
no JS o padrão é camel case, por isso não usamos _ pra nomear

2021-03-15 15:18 UTC, samycici commented on usuarios/put-usuarios.spec.js
> +    const response = await testServer.put(rota.rotaUsuarios + '/' + user_id)
```suggestion
    const response = await testServer.put(rota.rotaUsuarios + '/' + userId)
```
no JS o padrão é camel case, por isso não usamos _ pra nomear

2021-03-15 15:18 UTC, samycici commented on utils/userData.js
> +        return response_user
```suggestion
        return responseUser
```
no JS o padrão é camel case, por isso não usamos _ pra nomear

2021-03-15 15:18 UTC, samycici commented on usuarios/delete-usuarios.spec.js
> +beforeEach( async (done) => {
move esse before pra dentro do describe, assim na hora de ler o teste fica mais organizado em saber que essa pré-condição se aplica a qual teste

2021-03-15 15:18 UTC, samycici commented on usuarios/post-usuarios.spec.js
> +beforeEach(() => {
move esse before pra dentro do describe, assim na hora de ler o teste fica mais organizado em saber que essa pré-condição se aplica a qual teste

2021-03-15 15:18 UTC, samycici commented on usuarios/put-usuarios.spec.js
> +beforeEach( async (done) => {
move esse before pra dentro do describe, assim na hora de ler o teste fica mais organizado em saber que essa pré-condição se aplica a qual teste

2021-03-15 20:41 UTC, danielafdc commented on usuarios/put-usuarios.spec.js
> +beforeEach( async (done) => {
Samy, mas nesse caso eu quero que crie um usuário para os dois describes. Não vai ficar ruim ter 2 beforeEach aqui dentro?

2021-03-15 20:41 UTC, danielafdc commented on usuarios/post-usuarios.spec.js
> +beforeEach(() => {
Samy, mas nesse caso eu quero que crie um usuário para os dois describes... então, todos os testes. Não vai ficar ruim ter 2 beforeEach aqui dentro?

2021-03-15 20:48 UTC, samycici commented on usuarios/post-usuarios.spec.js
> +beforeEach(() => {
vc tem razão, não tinha reparado que eram dois describes globais, uma coisa que a gente costuma fazer é ter um describe global, do tipo:

`describe('POST /usuarios, () => {
}`

e ai dentro dele ter a estrutura de describes por cenario: Criar com sucesso, Não criar 

Dai o before ficaria dentro desse describe pai

2021-03-15 21:51 UTC, danielafdc commented
@samycici, terminei as alterações. Poderia revê-las?

2021-03-16 14:28 UTC, samycici approved these changes
<3

2021-03-16 14:28 UTC, merged